services:
  - type: web
    name: gym-app-prototype
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: REDIS_URL
        fromService:
          type: redis
          name: gym-redis
          property: connectionString

  - type: redis
    name: gym-redis
    plan: free # or starter for production
    ipAllowList: [] # internal access only
