services:
  - type: web
    name: gym-app-prototype
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: REDIS_URL
        fromService:
          type: redis
          name: gym-redis
          property: connectionString
      - key: DATABASE_URL
        fromService:
          type: psql
          name: gym-db
          property: connectionString

  - type: redis
    name: gym-redis
    plan: free # or starter for production
    ipAllowList: [] # internal access only

  - type: psql
    name: gym-db
    plan: free
    bgUser: admin
    bgPassword: password
    envVars:
      - key: POSTGRES_USER
        value: gym_user
      - key: POSTGRES_DB
        value: gym_db

