services:
  - type: web
    name: gym-app-prototype
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        fromDatabase:
          name: gym-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: gym-db
    plan: free
